"""Create table forecast_data.

Revision ID: b4289ac7f46f
Revises: 8736dfa98713
Create Date: 2025-08-26 17:54:47.421587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4289ac7f46f'
down_revision: Union[str, Sequence[str], None] = '8736dfa98713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_data_created_at'), 'forecast_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_data_date'), 'forecast_data', ['date'], unique=False)
    op.create_index(op.f('ix_forecast_data_updated_at'), 'forecast_data', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_data_updated_at'), table_name='forecast_data')
    op.drop_index(op.f('ix_forecast_data_date'), table_name='forecast_data')
    op.drop_index(op.f('ix_forecast_data_created_at'), table_name='forecast_data')
    op.drop_table('forecast_data')
    # ### end Alembic commands ###
