"""Create table forecast_data.

Revision ID: b4289ac7f46f
Revises: 8736dfa98713
Create Date: 2025-08-26 17:54:47.421587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4289ac7f46f'
down_revision: Union[str, Sequence[str], None] = '8736dfa98713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),

    sa.Column('night_icon', sa.String(length=4), nullable=True),
    sa.Column('night_text', sa.String(length=32), nullable=True),
    sa.Column('night_precip_mm', sa.Float(), nullable=True),
    sa.Column('night_temp_avg', sa.Float(), nullable=True),

    sa.Column('morning_icon', sa.String(length=4), nullable=True),
    sa.Column('morning_text', sa.String(length=32), nullable=True),
    sa.Column('morning_precip_mm', sa.Float(), nullable=True),
    sa.Column('morning_temp_avg', sa.Float(), nullable=True),

    sa.Column('afternoon_icon', sa.String(length=4), nullable=True),
    sa.Column('afternoon_text', sa.String(length=32), nullable=True),
    sa.Column('afternoon_precip_mm', sa.Float(), nullable=True),
    sa.Column('afternoon_temp_avg', sa.Float(), nullable=True),

    sa.Column('evening_icon', sa.String(length=4), nullable=True),
    sa.Column('evening_text', sa.String(length=32), nullable=True),
    sa.Column('evening_precip_mm', sa.Float(), nullable=True),
    sa.Column('evening_temp_avg', sa.Float(), nullable=True),

    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_data_created_at'), 'forecast_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_data_date'), 'forecast_data', ['date'], unique=True)
    op.create_index(op.f('ix_forecast_data_updated_at'), 'forecast_data', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_data_updated_at'), table_name='forecast_data')
    op.drop_index(op.f('ix_forecast_data_date'), table_name='forecast_data')
    op.drop_index(op.f('ix_forecast_data_created_at'), table_name='forecast_data')
    op.drop_table('forecast_data')
    # ### end Alembic commands ###
